### ISSUE TITLE
CTRL/FN swap

### ISSUE THREAD

**Issue by kocane** [Slion/TrackPointDriver#3]
Thanks a ton for the updated driver. Works very well.

Do you by any chance know if the driver can be modified so that the CTRL/FN button are swapped? or is that the job for firmware?

**Comment by Slion** [comment]
Glad you like it. I do not know that. That driver only deals with the mouse if I recall well so it's definitly not straight forward from this source code. Also getting it signed again might be tricky too.

**Comment by kocane** [comment]
@Slion - I think you're right - sure wish it was possible, but it seems unlikely :-( 

Now that you're here, and I hope it's ok I ask in this issue - how exactly can I go about utilizing the brightness control on the keyboard with DDC? I couldn't quite figure it out in your tool CIC.

Thanks for the reply!

**Comment by Slion** [comment]
You are out of luck, I think I broke the screen selection in the last CIC release and I'm not sure how you can install the previous release. On computer where it was already setup it still works though, unless you change your screen…
Not sure when I will get around fixing it.

**Comment by kocane** [comment]
@Slion Hmm, I'm not sure I understand. What's CIC?

**Comment by Slion** [comment]
> @Slion Hmm, I'm not sure I understand. What's CIC?

It's not exactly user friendly 😁 check out the events tab maybe.

**Comment by Slion** [comment]
See: https://slions.net/resources/command-information-center.4/

**Comment by kocane** [comment]
@Slion Ah of course, thanks! It couldn't detect my monitor but I used Autohotkey + Twinkle Tray to make a little exe that CIC could launch upon button press, to bring brightness up or down. Works well.

**Comment by Slion** [comment]
This year I ditched my mechanical keyboards for this:
https://slions.net/resources/interface.14/

It does support Ctrl and Fn swap 😁
