### ISSUE TITLE
1000Hz Polling rate

### ISSUE THREAD

**Issue by Wingklip** [Slion/TrackPointDriver#4]
I've been using trackpoints for centuries at this point, but I've found them always unreliable in the worst ways when the drivers and devices are made to the modern day's standards. 

Homing the trackpoint in firmware is always super crappy and sometimes results in the trackpoint flying across the screen for no reason but faulty and aggressive auto calibration.

I propose that one can solve it if the polling rate which defaults to about 72-100Hz, should be upped to at the least 250-500 Hz, and ideally 1000hz to make trackpoints viable as a gaming input device in 2023. And also so the damn thing doesn't skip across the screen and the buttons between the inputs thereof. 

It shouldn't take much but a driver thereof, maybe a modified jank implementation of sweetlow's signed mouse drivers. 

Everyone I'm sure is willing to donate to such a project, and by no means am I an exception to this.

**Comment by Slion** [comment]
It's very unlikely this driver will be further developed. Even if it was I doubt the current implementation will easily allow to change the polling rate.

**Comment by nefarius** [comment]
This is not possible without some additional redesign/rework since this driver doesn't sit at the required position in the driver stack to patch the necessary descriptors to "fool" the OS in upping the polling rate (at least for USB).
