### ISSUE TITLE
Using middle button for middle click

### ISSUE THREAD

**Issue by kocane** [Slion/TrackPointDriver#5]
Do you know if it's possible to make the middle button _also_ act as the regular middle click / mouse 3 button? It's my understanding that tpmiddle used to provide this behavior but it's not compatible with the SK-8855.

**Comment by Slion** [comment]
I think it should be possible. I am not planning to work on that anytime soon though. If I do I'll need to get @nefarius to kindly sign the drivers again.

**Comment by kocane** [comment]
@Slion another side question - do you know if this driver could be used with a "normal" synaptics trackpoint? I find the scrolling, after installing your driver, on my sk-8855 to my immensely superior to that of my T480.

**Comment by Slion** [comment]
@kocane I reckon it should work if you can locate the TrackPoint driver in the Windows Device Manager. It's worth a try anyway. If it fails you should be able re-install the original drivers right?

**Comment by kocane** [comment]
@Slion myeah, tried. It's coupled together with the synaptics driver I'm afraid so on dice. Ah well

**Comment by toanphuong** [comment]
Hi @Slion, I'm using USB Trackpoint keyboard model KU-1255 and setting up it with Slion Trackpoint Driver, but the both horizontal and vertical scrolling functions not working with Visual Studio Editor (Visual Studio IDE, not VS Code), it also crashes HScrollFunc.exe. Can you check this and make a fix? Thank you!

**Comment by Slion** [comment]
> I'm using USB Trackpoint keyboard model KU-1255

This driver was not designed or tested with this hardware.

> Can you check this and make a fix? 

I could, but I won't. I'm not using this hardware and I have no incentive to invest the hours of work needed to get this working. In fact I have not be using hardware keyboards for about a year since I switched to [Interface](http://interface.slions.net) on Galaxy Tab S8.

> Thank you!

You are welcome 😁

**Comment by nefarius** [comment]
These feature requests are not really possible to address without owning the affected hardware so the *least* invest the community would need to do is ship/gift/donate the hardware to @Slion (assuming time and interest still exists to work on the project). Anything else is black box development and a huge waste of time.

**Comment by Slion** [comment]
As mentioned above I eventually decided to stop using this hardware after what must have been about 15 years so it's highly unlikely I'll bother implementing new features. The original request about middle button should be doable though for anyone willing to invest a bit of time implementing and testing it.

**Comment by kocane** [comment]
@Slion glad you got to make this driver before abandoning the keyboard, it makes scrolling so much better!
